export const apiEndpoint = 'http://192.168.84.249:8000';
export const dataArsipsApi = apiEndpoint + '/api/arsips';
export const dataUsersApi = apiEndpoint + '/api/users';
export const storeArsip = apiEndpoint + '/api/arsips/store';
export const updateArsip = apiEndpoint + `/api/arsips/update`;
export const getListDocApi = apiEndpoint + '/api/getfiles';
export const storeUser = apiEndpoint + '/api/users/store';
export const destroyUser = apiEndpoint + '/api/users/destroy';
export const LoginUrl = apiEndpoint + '/api/login';
export const profileUser = apiEndpoint + '/api/users/profile';
export const editProfile = apiEndpoint + '/api/users/profile/edit'
